name: "Build/Test/Lint Rust Code"

on:
  push:

# Make sure workflow fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: Swatinem/rust-cache@v2

      - name: Build CLI Binary
        run: cargo build

      - name: Build Action Binary
        run: cargo build --bin md-table-action --features actions-runner-binary

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: Swatinem/rust-cache@v2

      - run: cargo test

  lint-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: Swatinem/rust-cache@v2

      - run: cargo clippy --all-targets --all-features

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: cargo fmt --check
